#ifndef	DATA_REGISTER_MACRO_H
#define	DATA_REGISTER_MACRO_H

#include <iostream>

#include "TpCore/JsonStructPackage/JsonStructBuffer.h"

#define JSON_NI_EXPAND(args) args

#define JSONTRANSLATION_0(c, p) convert(#p, c.p)
#define JSONTRANSLATION_1(c, p)  JSONTRANSLATION_0(c, p)
#define JSONTRANSLATION_2(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_1(c, __VA_ARGS__))
#define JSONTRANSLATION_3(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_2(c, __VA_ARGS__))
#define JSONTRANSLATION_4(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_3(c, __VA_ARGS__))
#define JSONTRANSLATION_5(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_4(c, __VA_ARGS__))
#define JSONTRANSLATION_6(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_5(c, __VA_ARGS__))
#define JSONTRANSLATION_7(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_6(c, __VA_ARGS__))
#define JSONTRANSLATION_8(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_7(c, __VA_ARGS__))
#define JSONTRANSLATION_9(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_8(c, __VA_ARGS__))
#define JSONTRANSLATION_10(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_9(c, __VA_ARGS__))
#define JSONTRANSLATION_11(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_10(c, __VA_ARGS__))
#define JSONTRANSLATION_12(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_11(c, __VA_ARGS__))
#define JSONTRANSLATION_13(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_12(c, __VA_ARGS__))
#define JSONTRANSLATION_14(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_13(c, __VA_ARGS__))
#define JSONTRANSLATION_15(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_14(c, __VA_ARGS__))
#define JSONTRANSLATION_16(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_15(c, __VA_ARGS__))
#define JSONTRANSLATION_17(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_16(c, __VA_ARGS__))
#define JSONTRANSLATION_18(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_17(c, __VA_ARGS__))
#define JSONTRANSLATION_19(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_18(c, __VA_ARGS__))
#define JSONTRANSLATION_20(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_19(c, __VA_ARGS__))
#define JSONTRANSLATION_21(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_20(c, __VA_ARGS__))
#define JSONTRANSLATION_22(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_21(c, __VA_ARGS__))
#define JSONTRANSLATION_23(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_22(c, __VA_ARGS__))
#define JSONTRANSLATION_24(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_23(c, __VA_ARGS__))
#define JSONTRANSLATION_25(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_24(c, __VA_ARGS__))
#define JSONTRANSLATION_26(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_25(c, __VA_ARGS__))
#define JSONTRANSLATION_27(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_26(c, __VA_ARGS__))
#define JSONTRANSLATION_28(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_27(c, __VA_ARGS__))
#define JSONTRANSLATION_29(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_28(c, __VA_ARGS__))
#define JSONTRANSLATION_30(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_29(c, __VA_ARGS__))
#define JSONTRANSLATION_31(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_30(c, __VA_ARGS__))
#define JSONTRANSLATION_32(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_31(c, __VA_ARGS__))
#define JSONTRANSLATION_33(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_32(c, __VA_ARGS__))
#define JSONTRANSLATION_34(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_33(c, __VA_ARGS__))
#define JSONTRANSLATION_35(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_34(c, __VA_ARGS__))
#define JSONTRANSLATION_36(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_35(c, __VA_ARGS__))
#define JSONTRANSLATION_37(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_36(c, __VA_ARGS__))
#define JSONTRANSLATION_38(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_37(c, __VA_ARGS__))
#define JSONTRANSLATION_39(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_38(c, __VA_ARGS__))
#define JSONTRANSLATION_40(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_39(c, __VA_ARGS__))
#define JSONTRANSLATION_41(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_40(c, __VA_ARGS__))
#define JSONTRANSLATION_42(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_41(c, __VA_ARGS__))
#define JSONTRANSLATION_43(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_42(c, __VA_ARGS__))
#define JSONTRANSLATION_44(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_43(c, __VA_ARGS__))
#define JSONTRANSLATION_45(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_44(c, __VA_ARGS__))
#define JSONTRANSLATION_46(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_45(c, __VA_ARGS__))
#define JSONTRANSLATION_47(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_46(c, __VA_ARGS__))
#define JSONTRANSLATION_48(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_47(c, __VA_ARGS__))
#define JSONTRANSLATION_49(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_48(c, __VA_ARGS__))
#define JSONTRANSLATION_50(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_49(c, __VA_ARGS__))
#define JSONTRANSLATION_51(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_50(c, __VA_ARGS__))
#define JSONTRANSLATION_52(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_51(c, __VA_ARGS__))
#define JSONTRANSLATION_53(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_52(c, __VA_ARGS__))
#define JSONTRANSLATION_54(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_53(c, __VA_ARGS__))
#define JSONTRANSLATION_55(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_54(c, __VA_ARGS__))
#define JSONTRANSLATION_56(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_55(c, __VA_ARGS__))
#define JSONTRANSLATION_57(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_56(c, __VA_ARGS__))
#define JSONTRANSLATION_58(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_57(c, __VA_ARGS__))
#define JSONTRANSLATION_59(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_58(c, __VA_ARGS__))
#define JSONTRANSLATION_60(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_59(c, __VA_ARGS__))
#define JSONTRANSLATION_61(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_60(c, __VA_ARGS__))
#define JSONTRANSLATION_62(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_61(c, __VA_ARGS__))
#define JSONTRANSLATION_63(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_62(c, __VA_ARGS__))
#define JSONTRANSLATION_64(c, p, ...) JSONTRANSLATION_0(c, p) . JSON_NI_EXPAND(JSONTRANSLATION_63(c, __VA_ARGS__))

#define JSON_NI_MAKE_CALL(t, f) t.f

#define JSON_NI_PARAMS_COUNT(TAG, _64,_63,_62,_61,_60, \
							_59,_58,_57,_56,_55,_54,_53,_52,_51,_50,\
							_49,_48,_47,_46,_45,_44,_43,_42,_41,_40,\
							_39,_38,_37,_36,_35,_34,_33,_32,_31,_30,\
							_29,_28,_27,_26,_25,_24,_23,_22,_21,_20,\
							_19,_18,_17,_16,_15,_14,_13,_12,_11,_10,\
								_9,_8,_7,_6,_5,_4,_3,_2,_1,N,...) TAG##N

#define JSONTRANSLATION(t, c, ...) JSON_NI_MAKE_CALL(t, JSON_NI_EXPAND(JSON_NI_PARAMS_COUNT(JSONTRANSLATION, __VA_ARGS__, _64,_63,_62,_61,_60, \
																								_59,_58,_57,_56,_55,_54,_53,_52,_51,_50,\
																								_49,_48,_47,_46,_45,_44,_43,_42,_41,_40,\
																								_39,_38,_37,_36,_35,_34,_33,_32,_31,_30,\
																								_29,_28,_27,_26,_25,_24,_23,_22,_21,_20,\
																								_19,_18,_17,_16,_15,_14,_13,_12,_11,_10,\
																								 _9,_8,_7,_6,_5,_4,_3,_2,_1))(c, __VA_ARGS__))

template<typename _Ty> struct JsonTypeTool{};
#define JSONTRANSLATE(_type, ...)	\
	template<> struct JsonTypeTool<_type>	\
	{	\
		template<typename _Ty>	\
		static void serlize(_Ty& t, _type& data)	\
		{	\
			JSONTRANSLATION(t, data, __VA_ARGS__);	\
		}	\
	};

#endif