G++ = g++
#源码路径
#SRC=../src
#头文件路径
#INC = -I../inc
INC = -I/usr/include \
        -I/usr/include/SDL2 \
        -I/usr/include/TinyPiX \
        -I/usr/include/TinyPiX/TpExtUtils \
        -I/usr/include/TinyPiX/TpUtils \
        -I/usr/include/TinyPiX/TpGUI \
        -I/usr/include/TinyPiX/TpGUI/Core \
        -I/usr/include/TinyPiX/TpGUI/Screen \
        -I/usr/include/TinyPiX/TpGUI/Widgets \
        -I.  \
        -I/usr/include/freetype2 \
        -I/usr/include/cairo \
        -I/usr/include/pango-1.0 \
        -I/usr/include/harfbuzz \
        -I/usr/include/glib-2.0 \
        -I/usr/lib/x86_64-linux-gnu/glib-2.0/include \
        -I/usr/include/TinyPiX/TpGUI/app \
        -I/usr/include/TinyPiX/TpWM -I/usr/include/TinyPiX/TpCore

#引用的库
#LIB = -lpthread -lpcap -ltparchive
LIB = -L/usr/lib \
        -ldl -lpthread -lSDL2  -lcairo -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lpangocairo-1.0  -lfontconfig -lfreetype -lgbm   -lGLESv2 -lEGL -lTpUtils  -lTpExtUtils -lTpGUI -lTpCore 
#伪目标：需要依赖的目标
#.PHONY:Audio Video Hard Record#即使该目标存在也重新生成
#all:Audio Video Hard Record clean#
.PHONY:Ap3216 #即使该目标存在也重新生成
all:Ap3216 clean#
Ap3216:
	$(G++) -c ap3216.cpp $(INC)
	$(G++) -c main.cpp $(INC)
	$(G++) -o Ap3216 ap3216.o main.o $(LIB) $(INC)
clean:
	rm *.o