#include <openobex/obex.h>
#include <openobex/obex_const.h>

typedef struct {
	char *name;
	int value;
} define;



extern define obex_modenames[];
extern define obex_evnames[];
extern define obex_hdrnames[];
extern define obex_cmdnames[];
extern define obex_rspnames[];

char *obex_name(int, define array[]); 

/* from: obex errata, for v1.3 */
#define OBEX_CMD_ACTION 0x06
#define OBEX_HDR_ACTION 0x94
//#define OBEX_HDR_DESTNAME 0x15
//#define OBEX_HDR_PERMISSIONS 0xd6

/* old version */
/*
#ifdef OBEX_MODE_CLIENT
#else
#define OBEX_MODE_CLIENT OBEX_CLIENT
#define OBEX_MODE_SERVER OBEX_SERVER
#endif*/

#ifdef OBEX_HDR_ID_MASK
#else
#define OBEX_HDR_ID_MASK		0x3f
#define OBEX_HDR_ID_EMPTY		OBEX_HDR_EMPTY & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_COUNT		OBEX_HDR_COUNT & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_NAME		OBEX_HDR_NAME & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_TYPE		OBEX_HDR_TYPE & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_LENGTH		OBEX_HDR_LENGTH & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_TIME		OBEX_HDR_TIME & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_TIME2		OBEX_HDR_TIME2 & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_DESCRIPTION		OBEX_HDR_DESCRIPTION & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_TARGET		OBEX_HDR_TARGET & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_HTTP		OBEX_HDR_HTTP & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_BODY		OBEX_HDR_BODY & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_BODY_END		OBEX_HDR_BODY_END & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_WHO			OBEX_HDR_WHO & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_CONNECTION		OBEX_HDR_CONNECTION & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_APPARAM		OBEX_HDR_APPARAM & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_AUTHCHAL		OBEX_HDR_AUTHCHAL & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_AUTHRESP		OBEX_HDR_AUTHRESP & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_CREATOR		OBEX_HDR_CREATOR & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_WANUUID		OBEX_HDR_WANUUID & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_OBJECTCLASS		OBEX_HDR_OBJECTCLASS & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_SESSIONPARAM	OBEX_HDR_SESSIONPARAM & OBEX_HDR_ID_MASK
#define OBEX_HDR_ID_SESSIONSEQ		OBEX_HDR_SESSIONSEQ & OBEX_HDR_ID_MASK
#endif

