# 平台不同拷贝资源文件到不同安装目录；以及准备不同平台的安装依赖库
# 首选方案：使用 CMAKE_CROSSCOMPILING 和自定义变量

# 检测交叉编译状态
if(CMAKE_CROSSCOMPILING)
    message(STATUS "============ 交叉编译;目标平台：${TARGET_ARCH} ============")
else()
    message(STATUS "============ 本机编译;目标平台：${TARGET_ARCH} ============")
endif()

# 首先检测指针大小以确定32位/64位架构[1,8](@ref)
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(ARCH_BIT 64)
elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
    set(ARCH_BIT 32)
else()
    set(ARCH_BIT 64)
endif()

if(DEFINED TARGET_ARCH)
    # 本机构建
    if(TARGET_ARCH STREQUAL "x86_64")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/x86_64")
        set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/x86_64" CACHE PATH "TinyPiXOS依赖的动态库目录")
        set(DEPEND_STATIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/static/x86_64" CACHE PATH "TinyPiXOS依赖的静态库目录")
    elseif(TARGET_ARCH STREQUAL "x86" OR TARGET_ARCH STREQUAL "i686")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/x86_32")
        set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/x86_32")
        set(DEPEND_STATIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/static/x86_32")
    elseif(TARGET_ARCH STREQUAL "arm64" OR TARGET_ARCH STREQUAL "aarch64")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/arm_64")
        set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/arm_64")
        set(DEPEND_STATIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/static/arm_64")
    elseif(TARGET_ARCH STREQUAL "arm" OR TARGET_ARCH STREQUAL "arm32" OR TARGET_ARCH MATCHES "armv7")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/arm_32")
        set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/arm_32")
        set(DEPEND_STATIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/static/arm_32")
    endif()
elseif(CMAKE_CROSSCOMPILING)
    # 交叉编译时获取目标架构
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64)$")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/arm_64")
        set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/arm_64")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm|armv[0-9]+|aarch32)$")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/arm_32")
        set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/arm_32")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64|AMD64)$")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/x86_64")
        set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/x86_64")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(i[3-6]86|i386|x86)$")
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/x86_32")
        set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/x86_32")
    else()
        message(WARNING "未知的目标平台架构: ${CMAKE_SYSTEM_PROCESSOR}")
        if(ARCH_BIT EQUAL 64)
            set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/x86_64")
            set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/x86_64")
        else()
            set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/x86_32")
            set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/x86_32")
        endif()
    endif()
    
else()
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64|AMD64)$" OR 
       (CMAKE_SYSTEM_PROCESSOR MATCHES "x86|i686|i386" AND ARCH_BIT EQUAL 64))
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/x86_64")
        set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/x86_64")
        set(DEPEND_STATIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/static/x86_64")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(i[3-6]86|i386|x86)$" AND ARCH_BIT EQUAL 32)
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/x86_32")
        set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/x86_32")
        set(DEPEND_STATIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/static/x86_32")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64)$" OR 
           (CMAKE_SYSTEM_PROCESSOR MATCHES "arm" AND ARCH_BIT EQUAL 64))
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/arm_64")
        set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/arm_64")
        set(DEPEND_STATIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/static/arm_64")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm|armv[0-9]+|aarch32)$" AND ARCH_BIT EQUAL 32)
        set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/arm_32")
        set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/arm_32")
        set(DEPEND_STATIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/static/arm_32")
    else()
        if(ARCH_BIT EQUAL 64)
            if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm")
                set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/arm_64")
                set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/arm_64")
                set(DEPEND_STATIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/static/arm_64")
            else()
                set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/x86_64")
                set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/x86_64")
                set(DEPEND_STATIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/static/x86_64")
            endif()
        else()
            if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm")
                set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/arm_32")
                set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/arm_32")
                set(DEPEND_STATIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/static/arm_32")
            else()
                set(INSTALL_PACKAGE_ROOT_PATH "${CMAKE_SOURCE_DIR}/install/x86_32")
                set(DEPEND_DYNAMIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/dynamic/x86_32")
                set(DEPEND_STATIC_LIB_PATH "${CMAKE_SOURCE_DIR}/src/depend_lib/static/x86_32")
            endif()
        endif()
    endif()
endif()

# 设置输出目录（根据架构和构建类型）
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${INSTALL_PACKAGE_ROOT_PATH}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${INSTALL_PACKAGE_ROOT_PATH}/lib)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${INSTALL_PACKAGE_ROOT_PATH}/lib)
